osx_image: xcode10
language: swift

before_install:
#  - brew upgrade swiftlint

jobs:
  include:
    - stage: iOS Test # Run tests
      script: fastlane ios test
    - stage: iOS Lint # Run linter
      script: fastlane ios lint
