name: Beta Release
on:
  push:
    tags:
      - v*.*.*
jobs:
  test:
    name: TestFlight
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: XCode Setup
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.1'
      - uses: actions/cache@v2
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Carthage
        run: |
          ./carthage.sh bootstrap --no-use-binaries --platform iOS --cache-builds
      - name: Build and test
        run: |
          bundle install && CI=1 bundle exec fastlane beta
        env:
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
